In [63]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [128]:
import numpy as np 
#np artık numpy demek

In [129]:
# numpy arrays

In [130]:
my_list = [10, 20, 30, 40]

In [131]:
type(my_list)

list

In [132]:
np.array(my_list)

array([10, 20, 30, 40])

In [133]:
my_numpy_array = np.array(my_list)

In [134]:
type(my_numpy_array)

numpy.ndarray

In [135]:
my_numpy_array

array([10, 20, 30, 40])

In [136]:
my_numpy_array[-1]
#Normal dizilerden farkı yok ama numpy dizilerinin baska ozellikleri de var

40

In [137]:
my_numpy_array.max()

40

In [138]:
my_numpy_array.min()

10

In [139]:
my_numpy_array.mean()
#ortalama alır

25.0

In [76]:
matrix_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [77]:
matrix_list[0]

[1, 2, 3, 4]

In [78]:
matrix_list[0][0]

1

In [79]:
np.array(matrix_list)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [140]:
np.array(matrix_list)[0][3]

4

In [81]:
np.array(matrix_list).shape
#4 satir 4 sutun oldugunu gosterir.

(4, 4)

arange

In [145]:
np.arange(100, 155)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154])

In [150]:
np.zeros((10, 16))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

linspace

In [151]:
np.linspace(0,10,3)
#linspace(basNoktasi, bitNoktasi, eleman sayisi)
#ilk elemanı 0 oluyor düzenli artırarak son elemanı 10 yapıyor.

array([ 0.,  5., 10.])

In [154]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

random

In [158]:
np.random.randint(0, 10)
#1'den 10'a kadar herhangi bir rakam veriyor.

3

In [161]:
np.random.randint(1, 10, 5)
#1'den 10'a kadar herhangi 5 rakam veriyor. Hem de numpy array şeklinde

array([1, 5, 2, 8, 4])

In [162]:
np.random.randint(0, 100, 10)

array([44, 70, 36, 78,  6, 97,  0, 83, 34, 71])

In [90]:
#numpy dizisi normal python listesinden ayrı bir yapıdır. Veri biliminde kullanılır.

numpy arrays methods

In [91]:
my_numpy_list = np.arange(0, 20)

In [92]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
my_numpy_list[4]

4

In [94]:
my_numpy_list[4:17:3]

array([ 4,  7, 10, 13, 16])

In [95]:
my_list = list(range(0, 20))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [96]:
my_list[4:9:2]

[4, 6, 8]

In [97]:
#my_list[4:9] = 10 dersek hata alırız çünkü normal listelerin böyle bir özelliği yok

In [98]:
my_numpy_list[4:9] = -10

In [99]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [100]:
other_list = np.arange(0,15)
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
slicing_list = other_list[4:10]
slicing_list

array([4, 5, 6, 7, 8, 9])

In [102]:
slicing_list[:] = 100
slicing_list

array([100, 100, 100, 100, 100, 100])

In [103]:
other_list
#görüldüğü üzere other_list'i değiştirmememize rağmen o da değişmiş. Bu numpy'da bir kuraldır mantığı yoktur. Normalde 
#dizilerde böyle bir şey yok

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [104]:
numpy_list_3 = np.arange(0, 20)

In [105]:
numpy_list_3_copy = numpy_list_3.copy()

In [106]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
slicing_3 = numpy_list_3_copy[4:9]

In [108]:
slicing_3[:] = -100

In [109]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [110]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
#numpy_list_3' kopyaladığımız için değişmesinin önüne geçtik

numpy operations with numpy arrays

In [112]:
new_array = np.random.randint(1, 150, 25)
new_array

array([ 46,  81,  26, 113,  15,  38,  25,   4,   4, 119,  89, 149,  94,
        45,  79,  86,  43, 124,  39,  63,  54,  19,  72, 118,  78])

In [113]:
new_array > 50

array([False,  True, False,  True, False, False, False, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True])

In [114]:
result_array = new_array > 50

In [115]:
result_array

array([False,  True, False,  True, False, False, False, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True])

In [116]:
new_array[result_array]
# sadece 50 den büyük sayıları döndüren sayıları verdi

array([ 81, 113, 119,  89, 149,  94,  79,  86, 124,  63,  54,  72, 118,
        78])

In [117]:
last_array = np.arange(0, 30)

In [118]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [119]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [120]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [121]:
last_array -last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [122]:
last_array.max()

29

In [163]:
np.max(last_array)
#ikisi de aynı

29

In [124]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])